[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.160.1"
  HUGO_BASEURL = "https://gazikabas.github.io"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"